### ISSUE TITLE
Finishing the ConSet

### ISSUE THREAD

**Issue by vorner** [vorner/contrie#2]
The master already contain the `ConSet` type, with basic set of methods. However, two things are missing:

- [x] Tests
- [x] Iterator related traits (`Extend`, `.iter`, `IntoIter` for reference and `FromIter`).

The `ConSet` type is very similar to the `ConMap` one, so the implementations of the above will end up being similar too. Few notable things:

* The tests of ConMap also indirectly test the underlying implementation that is shared. There's no need to do as thorough tests once again with sets (like all the multi-threaded inserts). Few tests that try to call each method in one or two scenarios should be enough.
* The ConMap `Extend` and `FromIter` work both on tuples `(K, V)` and prepared `Arc<Element>`s. The set has no such thing, they would simply take `T` directly.

If considering working on this, please write a comment to claim the issue (and specify if you want to tackle both or only one of the subtasks). It is fine to put into review in parts as smaller pull requests or as one bigger, as you prefer.

Don't hesitate to ask if you have any questions or want some help.

**Comment by zeroed** [comment]
Hey @vorner , thank you for opening your project at _GoodFirstIssues_; I'm reading/studying a bit around the topic of concurrent data structures and I hope to get more understanding starting with some small contribution.

I still have to properly get into the details of the [paper](https://www.researchgate.net/publication/221643801_Concurrent_Tries_with_Efficient_Non-Blocking_Snapshots) that you linked and of your implementation; needless to say it's quite interesting. 

There is some **work-in-progress** in #4; any comment is more than welcome and feel free to drop there any consideration. Thanks in advance.

**Comment by vorner** [comment]
You're welcome, I'll be glad to get some contributions :-).

As for studying, few notes:
* These „good first issue“ tasks are meant to be possible without understanding the concurrent parts, they are hidden inside the raw module. Nevertheless, I'll appreciate if you read through the raw module as well ‒ and I'll be glad for any clarifications in the comments, pointing out of things that I've overlooked, etc, or even making the code more readable (which I'm less able to judge as he author).
* My implementation is only inspired by the paper, but is simplified a lot. So I think it makes sense to read the implementation first and then proceed to the paper.

I'll get around to looking at the code soon, but I won't promise it'll be today (maybe, maybe not).

**Comment by vorner** [comment]
OK, this seems to be completed, so closing.

If anyone is looking for further easy tasks, I'll make sure to get around to creating few more soon.
